### ISSUE TITLE
could you please include cookie

### ISSUE THREAD

**Issue by OnlyDaft** [Euronymou5/Roblox-Phish#2]
could you please include cookie and a feature where it sends to the webhook

**Comment by Euronymou5** [comment]
Sure, I'll work as soon as I can on making a cookie grabber method.

**Comment by OnlyDaft** [comment]
tysm, I figured out roblox cookies might not work. so could u add .rbxid and make it try sending to webhook? u dont need to make it send to webhook but it is more convenient. thanks :)

**Comment by OnlyDaft** [comment]
btw, does the site bypass CORS? I need a roblox phishing site bypassing CORS

**Comment by Euronymou5** [comment]
> tysm, I figured out roblox cookies might not work. so could u add .rbxid and make it try sending to webhook? u dont need to make it send to webhook but it is more convenient. thanks :)

Could you explain a little more about that? I don't know many Roblox things like that because I don't focus as such on the development of that kind of thing for Roblox
